version: '3'
services:
  datascience_test:
    image: jupyter/scipy-notebook:latest
    volumes:
      - ./container:/home/jovyan/container
    ports:
      - "8888:8888"
    user: root
    command: /bin/sh -c "jupyter notebook --ip='*' --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''"
