version: '3'
services:
  datascience_test:
    image: jupyter/scipy-notebook:latest
    env_file:
        - .env
    volumes:
      - ${LOCAL_WORKING_DIR}:/notebook
      - ${LOCAL_SSL_CERTS}:/notebook/ssl
    ports:
      - ${PORT}:8888
    command: "start-notebook.sh"
    user: root
